### ISSUE TITLE
maybe use this for tablular output? 

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/spiced_gracken#1]
https://github.com/tj/terminal-table

**Comment by NullVoxPopuli** [comment]
this one looks like it will limit itself to the width of the window - and looks a little better: https://github.com/arches/table_print

**Comment by NullVoxPopuli** [comment]
meh

**Comment by etkirsch** [comment]
Why closed?

**Comment by NullVoxPopuli** [comment]
I'm not going to use it, I was going to use it to help draw my own UI, but I have curses now.
